# Introduction to Tensors

Tensors are multi-dimensional arrays that are fundamental to data representation in machine learning and deep learning. In Python, you can work with tensors using libraries like NumPy and TensorFlow.

In [6]:
import numpy as np
import tensorflow as tf

In [8]:
print("Numpy Version: ", np.__version__)
print("Tensorflow Version: ", tf.__version__)

Numpy Version:  1.24.3
Tensorflow Version:  2.13.1


## Vectors

A vector is a one dimensional tensor

In [18]:
vector_tf = tf.constant([1,2,3,4,5])
vector_np = np.array([1,2,3,4,5])

print("tf vector shape: ", vector_tf.shape)
print("np vector shape: ", vector_np.shape)

#print(vector_tf)
#print(vector_np)


tf vector shape:  (5,)
np vector shape:  (5,)


## Matrix

A matrix is a two dimensional tensor

In [19]:
matfix_tf = tf.constant([[1,2],[3,4],[5,6]])
matfix_np = np.array([[1,2],[3,4],[5,6]])

print("tf matrix shape: ", matfix_tf.shape)
print("np matrix shape: ", matfix_np.shape)

#print(matfix_tf)
#print(matfix_np)


tf matrix shape:  (3, 2)
np matrix shape:  (3, 2)


## 3 Dimensional Tensors

Tensors can be n dimensional

In [23]:
t3_tf = tf.constant([[[1,2],[3,4],[5,6]]] * 5)
t3_np = np.array([[[1,2],[3,4],[5,6]]] * 5)

print("t3_tf shape: ", t3_tf.shape)
print("t3_np shape: ", t3_np.shape)

# Whenever a tensor is printed, it will show you the values and datatype
# print(t3_tf)
# print(t3_np)


t3_tf shape:  (5, 3, 2)
t3_np shape:  (5, 3, 2)


## Declaring Tensors

There are 2 types of tensors.
constant and variable

In [25]:
const_tensor = tf.constant([[1,2,3], [4,5,6]])
var_tensor = tf.Variable([[1,2,3], [4,5,6]])

Tensors can be declared with specific datatypes

In [27]:
int32_tensor = tf.Variable([[[1,2], [3,4]]], dtype=tf.int32)
flaot32_tensor = tf.Variable([[[1.0,2.2], [3.01,4.21893]]], dtype=tf.float32)
bool_tensor = tf.Variable([[[True,False], [True,True]]], dtype=tf.bool)

print(int32_tensor)
print(flaot32_tensor)
print(bool_tensor)

<tf.Variable 'Variable:0' shape=(1, 2, 2) dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(1, 2, 2) dtype=float32, numpy=
array([[[1.     , 2.2    ],
        [3.01   , 4.21893]]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(1, 2, 2) dtype=bool, numpy=
array([[[ True, False],
        [ True,  True]]])>


Tensors can be converted to numpy array using the function numpy()

In [28]:
int32_tensor.numpy()

array([[[1, 2],
        [3, 4]]], dtype=int32)

## Mathematical Operations on Tensors

### Element wise common mathematical operations

In [35]:
x = tf.Variable([list(range(4))]*6)
y = x + 3

print("x: ", x)
print("y: ", y)

x:  <tf.Variable 'Variable:0' shape=(6, 4) dtype=int32, numpy=
array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int32)>
y:  tf.Tensor(
[[3 4 5 6]
 [3 4 5 6]
 [3 4 5 6]
 [3 4 5 6]
 [3 4 5 6]
 [3 4 5 6]], shape=(6, 4), dtype=int32)


In [36]:
z = x + y 
# Equivalent Function would be
# z = tf.add(x,y)
print("z: ", z)

z:  tf.Tensor(
[[3 5 7 9]
 [3 5 7 9]
 [3 5 7 9]
 [3 5 7 9]
 [3 5 7 9]
 [3 5 7 9]], shape=(6, 4), dtype=int32)


In [37]:
z = x - y
# Equivalent Function would be
# z = tf.subtract(x,y)
print("z: ", z)

z:  tf.Tensor(
[[-3 -3 -3 -3]
 [-3 -3 -3 -3]
 [-3 -3 -3 -3]
 [-3 -3 -3 -3]
 [-3 -3 -3 -3]
 [-3 -3 -3 -3]], shape=(6, 4), dtype=int32)


In [38]:
z = x * y
# Equivalent Function would be
# z = tf.multiply(x,y)
print("z: ", z)

z:  tf.Tensor(
[[ 0  4 10 18]
 [ 0  4 10 18]
 [ 0  4 10 18]
 [ 0  4 10 18]
 [ 0  4 10 18]
 [ 0  4 10 18]], shape=(6, 4), dtype=int32)


In [39]:
z = x/y
# Equivalent Function would be
# z = tf.divide(x,y)
print("z: ", z)

z:  tf.Tensor(
[[0.   0.25 0.4  0.5 ]
 [0.   0.25 0.4  0.5 ]
 [0.   0.25 0.4  0.5 ]
 [0.   0.25 0.4  0.5 ]
 [0.   0.25 0.4  0.5 ]
 [0.   0.25 0.4  0.5 ]], shape=(6, 4), dtype=float64)


**NOTE: Element wise operations will not work if both tensors are of different shapes**

### Linear Algebra on Tensors

#### Matrix Multiplication using matmul function in the linalg library

In [42]:
matrix_A = tf.constant([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix
matrix_B = tf.constant([[7, 8], [9, 10], [11, 12]])  # 3x2 matrix

result = tf.linalg.matmul(matrix_A, matrix_B)

print("matrix_A: ", matrix_A)
print("matrix_B: ", matrix_B)
print("Result of Matrix Multiplication:", result)

matrix_A:  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
matrix_B:  tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Result of Matrix Multiplication: tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


#### Finding the inverse of a matrix using the inv functionj in the linalg library

**Not all matrices have inverses. For a matrix to have an inverse, it must be square (having the same number of rows and columns) and have a non-zero determinant. If the matrix is singular (no inverse exists), you may encounter an error or a result with NaN values.**

In [ ]:
matrix_A = tf.constant([[1.0, 2.0], [3.0, 4.0]])

inverse_A = tf.linalg.inv(matrix_A)

print("matrix_A:", matrix_A)
print("\nInverse of the Matrix:", inverse_A)

**When you try to find the inverse of a matrix using tf.linalg.inv, the input matrix must have a data type of float32 or float64. You cannot directly find the inverse of a matrix with an integer data type using this function.**

If you attempt to run the code above, you'll encounter an error similar to the following:
**InvalidArgumentError: Matrix is not invertible.**

#### Solving a linear equation with 4 variables

Suppose we have the following linear system of equations:

2x + 3y + z - w = 10
x - 2y + 2z + 2w = -4
3x + y - z + 3w = 6
4x - y + 3z - w = 2

We can represent this system of equations in matrix form as Ax = b, where A is the coefficient matrix, x is the vector of variables [x, y, z, w], and b is the vector of constants on the right-hand side.


In [52]:
# Define the coefficient matrix A
A = tf.constant([[2.0, 3.0, 1.0, -1.0],
                 [1.0, -2.0, 2.0, 2.0],
                 [3.0, 1.0, -1.0, 3.0],
                 [4.0, -1.0, 3.0, -1.0]], dtype=tf.float32)

# Define the vector of constants b
b = tf.constant([[10.0], [-4.0], [6.0], [2.0]], dtype=tf.float32)

Let's solve it step by step:

- Define the coefficient matrix A and the vector of constants b.
- Calculate the inverse of A using tf.linalg.inv.
- Multiply the inverse of A with b to find the solution vector x.

In [53]:
# Calculate the inverse of A
A_inv = tf.linalg.inv(A)

# Calculate the solution x by multiplying A_inv with b
x = tf.matmul(A_inv, b)

# Display the solution
print("Solution:")
print(x.numpy())

Solution:
[[ 1.1428572e+00]
 [ 2.5714288e+00]
 [ 1.4901161e-08]
 [-5.9604645e-08]]



The code defines the coefficient matrix A and the vector of constants b, and then uses tf.linalg.solve to find the solution vector x. The result will be the values of the variables x, y, z, and w that satisfy the system of equations.


### A Practical Use of algebraic equations with tensor flow

The weights and bias term of a trained model logistic regression model are given below.  

w1 = 0.5, w2 = 1 , w3 = -1.2 

b = 0.01

The features of a data point are given below.

​x1 = 0.2, x2 = 1, x3 = 0.5

Using TensorFlow, find the probability of the data point belonging to the positive class.

To find the probability of a data point belonging to the positive class in a logistic regression model with given weights and bias, you can use the logistic sigmoid function. 

Here's how you can do it using TensorFlow:


In [54]:
# Define the weights and bias
w1 = 0.5
w2 = 1
w3 = -1.2
b = 0.01

# Define the features of the data point
x1 = 0.2
x2 = 1
x3 = 0.5

# Calculate the linear combination of weights and features
z = w1 * x1 + w2 * x2 + w3 * x3 + b

# Apply the logistic sigmoid function to get the probability
probability = tf.sigmoid(z)

# Display the probability
print("Probability of the data point belonging to the positive class:", probability.numpy())

Probability of the data point belonging to the positive class: 0.62480646


In this code:

We first define the weights w1, w2, w3, and the bias b as given.

We define the features x1, x2, and x3 of the data point.

We calculate the linear combination z of weights and features as z = w1 * x1 + w2 * x2 + w3 * x3 + b.

We apply the logistic sigmoid function using tf.sigmoid(z) to obtain the probability of the data point belonging to the positive class.

Running this code will give you the probability of the data point belonging to the positive class based on the logistic regression model with the provided weights and bias.